trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    exclude:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - '*.md'
    - LICENSE

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  BuildConfiguration: 'Release'
  COREHOST_TRACE: 0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- script: dotnet --info
  displayName: Display dotnet SDK information

- script: dotnet build --configuration $(BuildConfiguration)
  displayName: Build solution
  failOnStderr: true

- script: dotnet test --no-build --logger trx
  displayName: Run tests
  failOnStderr: true

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet pack --no-build --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: Create NuGet package
  failOnStderr: true

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
