trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - *.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  COREHOST_TRACE: 0
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- script: |
    dotnet build --configuration $(buildConfiguration)
    dotnet test --no-build --configuration $(buildConfiguration) --logger trx
    dotnet pack --no-build --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  failOnStderr: true

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
